//! This module implements a SMB2 negotiate response.
//! The SMB2 NEGOTIATE Response packet is sent by the server to notify the client of the preferred common dialect.
//! This response is composed of an SMB2 header, followed by this response structure.

use crate::smb2::handshake_helper::{fields::SecurityMode, negotiate_context::NegotiateContext};

/// negotiate response size of 65 bytes
const STRUCTURE_SIZE: &[u8; 2] = b"\x41\x00";

/// The SMB2 NEGOTIATE Response packet is sent by the server to notify
/// the client of the preferred common dialect. This response is composed of an
/// SMB2 header, followed by this response structure.
#[derive(Debug, PartialEq, Eq, Clone)]
pub struct Negotiate {
    /// StructureSize (2 bytes): The server MUST set this field to 65,
    /// indicating the size of the response structure, not including the header.
    /// The server MUST set it to this value, regardless of the number of
    /// negotiate contexts or how long Buffer[] actually is in the response being sent.
    pub structure_size: Vec<u8>,
    /// SecurityMode (2 bytes): The security mode field specifies whether SMB signing is enabled,
    /// required at the server, or both. This field MUST be constructed using the following values.
    pub security_mode: Option<SecurityMode>,
    /// DialectRevision (2 bytes): The preferred common SMB 2 Protocol dialect number from the
    /// Dialects array that is sent in the SMB2 NEGOTIATE Request or the SMB2 wildcard revision number.
    /// The server SHOULD set this field to one of the following values.
    pub dialect_revision: Option<DialectRevision>,
    /// NegotiateContextCount/Reserved (2 bytes): If the DialectRevision field is 0x0311,
    /// this field specifies the number of negotiate contexts in NegotiateContextList;
    /// otherwise, this field MUST NOT be used and MUST be reserved.
    /// The server SHOULD set this to 0, and the client MUST ignore it on receipt.
    pub negotiate_context_count: Vec<u8>,
    /// ServerGuid (16 bytes): A globally unique identifier (GUID) that is generated by the
    /// server to uniquely identify this server. This field MUST NOT be used by a client
    /// as a secure method of identifying a server.
    pub server_guid: Vec<u8>,
    /// Capabilities (4 bytes): The Capabilities field specifies protocol capabilities for the server.
    pub capabilities: Vec<u8>,
    /// MaxTransactSize (4 bytes): The maximum size, in bytes, of the buffer that can be used for
    /// QUERY_INFO, QUERY_DIRECTORY, SET_INFO and CHANGE_NOTIFY operations.
    /// This field is applicable only for buffers sent by the client in SET_INFO requests,
    /// or returned from the server in QUERY_INFO, QUERY_DIRECTORY, and CHANGE_NOTIFY responses.
    pub max_transact_size: Vec<u8>,
    /// MaxReadSize (4 bytes): The maximum size, in bytes, of the Length in an SMB2 READ Request
    /// that the server will accept.
    pub max_read_size: Vec<u8>,
    /// MaxWriteSize (4 bytes): The maximum size, in bytes, of the Length in an SMB2 WRITE Request
    /// that the server will accept.
    pub max_write_size: Vec<u8>,
    /// SystemTime (8 bytes): The system time of the SMB2 server when the SMB2 NEGOTIATE Request was
    /// processed in FILETIME format.
    pub system_time: Vec<u8>,
    /// ServerStartTime (8 bytes): The SMB2 server start time, in FILETIME format
    pub server_start_time: Vec<u8>,
    /// SecurityBufferOffset (2 bytes): The offset, in bytes, from the beginning
    /// of the SMB2 header to the security buffer.
    pub security_buffer_offset: Vec<u8>,
    /// SecurityBufferLength (2 bytes): The length, in bytes, of the security buffer.
    pub security_buffer_length: Vec<u8>,
    /// NegotiateContextOffset/Reserved2 (4 bytes): If the DialectRevision field is 0x0311,
    /// then this field specifies the offset, in bytes, from the beginning of the SMB2 header
    /// to the first 8-byte aligned negotiate context in NegotiateContextList; otherwise,
    /// the server MUST set this to 0 and the client MUST ignore it on receipt.
    pub negotiate_context_offset: Vec<u8>,
    /// Buffer (variable): The variable-length buffer that contains the security buffer for the response,
    /// as specified by SecurityBufferOffset and SecurityBufferLength. The buffer SHOULD contain a token
    /// as produced by the GSS protocol. If SecurityBufferLength is 0, this field is empty and then
    /// client-initiated authentication, with an authentication protocol of the client's choice,
    /// will be used instead of server-initiated SPNEGO authentication.
    pub buffer: Vec<u8>,
    /// Padding (variable): Optional padding between the end of the  Buffer field and the first
    /// negotiate context in the NegotiateContextList so that the first negotiate context is 8-byte aligned.
    pub padding: Vec<u8>,
    /// NegotiateContextList (variable): If the DialectRevision field is 0x0311, a list of negotiate contexts.
    /// The first negotiate context in the list MUST appear at the byte offset indicated by the
    /// SMB2 NEGOTIATE response's NegotiateContextOffset. Subsequent negotiate contexts MUST appear
    /// at the first 8-byte aligned offset following the previous negotiate context.
    pub negotiate_context_list: Vec<NegotiateContext>,
}

impl Negotiate {
    pub fn default() -> Self {
        Negotiate {
            structure_size: STRUCTURE_SIZE.to_vec(),
            security_mode: None,
            dialect_revision: None,
            negotiate_context_count: Vec::new(),
            server_guid: Vec::new(),
            capabilities: Vec::new(),
            max_transact_size: Vec::new(),
            max_read_size: Vec::new(),
            max_write_size: Vec::new(),
            system_time: Vec::new(),
            server_start_time: Vec::new(),
            security_buffer_offset: Vec::new(),
            security_buffer_length: Vec::new(),
            negotiate_context_offset: Vec::new(),
            buffer: Vec::new(),
            padding: Vec::new(),
            negotiate_context_list: Vec::new(),
        }
    }
}

/// DialectRevision (2 bytes): The preferred common SMB 2 Protocol dialect number
/// from the Dialects array that is sent in the SMB2 NEGOTIATE Request or the SMB2 wildcard revision number.
/// The server SHOULD set this field to one of the following values.
#[derive(Debug, PartialEq, Eq, Clone)]
pub enum DialectRevision {
    SMB202,
    SMB21,
    SMB30,
    SMB302,
    SMB311,
    Wildcard,
}

impl DialectRevision {
    /// Unpacks the byte code for the dialect revision.
    pub fn unpack_byte_code(&self) -> Vec<u8> {
        match self {
            DialectRevision::SMB202 => b"\x02\x02".to_vec(),
            DialectRevision::SMB21 => b"\x10\x02".to_vec(),
            DialectRevision::SMB30 => b"\x00\x03".to_vec(),
            DialectRevision::SMB302 => b"\x02\x03".to_vec(),
            DialectRevision::SMB311 => b"\x11\x03".to_vec(),
            DialectRevision::Wildcard => b"\xff\x02".to_vec(),
        }
    }

    /// Maps the byte code of a incoming response to the corresponding dialect.
    pub fn map_byte_code_to_dialect(byte_code: Vec<u8>) -> DialectRevision {
        match byte_code.as_slice() {
            [2, 2] => DialectRevision::SMB202,
            [16, 2] => DialectRevision::SMB21,
            [0, 3] => DialectRevision::SMB30,
            [2, 3] => DialectRevision::SMB302,
            [17, 3] => DialectRevision::SMB311,
            [255, 2] => DialectRevision::Wildcard,
            _ => panic!("Invalid dialect."),
        }
    }
}
